# Gradle
org.gradle.jvmargs=-Xmx8G
org.gradle.parallel=true

# Base
mod_name=Blitz
mod_version=1.0.0
mod_group=com.mememan
mod_authors=Meme Man
mod_id=blitz
mod_license=MIT License
mod_description=Oneshot content mod that adds a couple of utility items, as well as a fun little bossfight.

minecraft_version=1.20.1
fabric_loom_version=1.15-SNAPSHOT
publisher_plugin_version=0.5.2

mappings_channel_version=1.20.1:2023.09.03

mixinextras_version=0.5.3
fabric_loader_version=0.18.4

minecraft_version_range=1.20.1
fabric_loader_version_range=>=0.18.4

mod_icon_path=blitz_logo.png

homepage_url=
source_code_url=https://github.com/RaveTr/Blitz
issue_tracker_url=https://github.com/RaveTr/Blitz/issues

fabric_common_entrypoint=com.mememan.blitz.Blitz
fabric_client_entrypoint=com.mememan.blitz.BlitzClient

fabric_modmenu_entrypoint=com.mememan.blitz.core.integration.modmenu.ModMenuEntrypoint

fabric_client_taskname=Blitz Fabric Client
fabric_server_taskname=Blitz Fabric Server
fabric_data_taskname=Blitz Fabric DataGen

# Dependencies (Required)
fabric_api_version=0.92.7+1.20.1
nexus_version=1.0.9

fabric_api_version_range=>=0.92.7+1.20.1
nexus_version_range=>=1.0.9

# Dependencies (Optional)
jei_version=15.2.0.27
appleskin_version=mc1.20-2.5.1
modmenu_version=7.2.2

jei_version_range=>=15.2.0.27
appleskin_version_range=>=mc1.20-2.5.1
modmenu_version_range=>=7.2.2
